name: Staging Build pipleine

on:
  push:
    branches:
      - develop

jobs:
  build_and_test:
    name: Rust shorten url project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Build
        run: cargo build --release --all-features
      # - name: Build Docker image
      #   run: docker build -t registry.heroku.com/${{ secrets.HEROKU_APP }}/web:latest .
      #   run: docker build 

      # - name: Docker image info
      #   run: docker images
